#!/bin/sh

lb config noauto \
    --distribution bookworm \
    --architectures amd64 \
    --archive-areas "main contrib non-free non-free-firmware" \
    --binary-images iso-hybrid \
    --bootloaders "syslinux,grub-efi" \
    --debian-installer live \
    --debian-installer-distribution bookworm \
    --debian-installer-gui true \
    --security true \
    --updates true \
    --apt-recommends true \
    --firmware-binary true \
    --firmware-chroot true \
    --iso-application "SylonOS" \
    --iso-publisher "SylonOS Project" \
    --iso-volume "SylonOS 1.0" \
    --bootappend-live "boot=live components locales=fr_FR.UTF-8 keyboard-layouts=fr splash quiet" \
    --bootappend-install "auto=true priority=critical preseed/file=/cdrom/preseed.cfg locale=fr_FR.UTF-8 keyboard-configuration/xkb-keymap=fr" \
    --source false \
    "${@}"
